<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Nokt.Ui</RootNamespace>
    <AssemblyName>Nokt.Ui</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\nk\Nokt.csproj" />
  </ItemGroup>
</Project>
